server:
  port: '8085'
management:
  endpoints:
    web:
      exposure:
        include: bindings
spring:
  rabbitmq:
    username: admin
    password: admin
  cloud:
    stream:
      source: producer
      default-binder: rabbit
      bindings:
        consumer-in-0:
          destination: requests
          group: eoloplantCreationRequests
#          destination: eoloplantCreationRequests
        producer-out-0:
          destination: progress
          group: eoloplantCreationProgressNotifications
          producer:
            required-groups: eoloplantCreationProgressNotifications
      rabbit:
        binder:
          nodes: 'localhost:5672'
        bindings:
          consumer-in-0:
            consumer:
              queue-name-group-only: 'true'
          producer-out-0:
            producer:
              queue-name-group-only: 'true'

