server:
  port: '8085'
management:
  endpoints:
    web:
      exposure:
        include: bindings
spring:
#  rabbitmq:
#    username: admin
#    password: admin
  cloud:
    stream:
      default-binder: kafka
      bindings:
        consumer-in-0:
          destination: eoloplantCreationRequests
        producer-out-0:
          destination: eoloplantCreationProgressNotifications
          producer:
            required-groups: eoloplantCreationProgressNotifications
      rabbit:
        binder:
          nodes: 'localhost:5672'
        bindings:
          consumer-in-0:
            consumer:
              queue-name-group-only: 'true'
          producer-out-0:
            producer:
              queue-name-group-only: 'true'
      kafka:
        binder:
          reset-offset: true
          start-offset: latest
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
          # Specify the number of copies of Topic
          replication-factor: 1
          configuration:
            max.request.size: 20000000
          brokers:
            - localhost:9092

