server:
  port: '8085'
management:
  endpoints:
    web:
      exposure:
        include: bindings
spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        consumer-in-0:
          destination: eoloplantCreationRequests
        producer-out-0:
          destination: eoloplantCreationProgressNotifications
      kafka:
        binder:
          reset-offset: true
          start-offset: latest
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
          # Specify the number of copies of Topic
          replication-factor: 1
          configuration:
            max.request.size: 20000000
          brokers:
            - localhost:9092

